### ISSUE TITLE
Map - modify HHI logic to support new data format

### ISSUE THREAD

**Issue by JackBlake-zkq** [DSSD-Madison/Red-CORAL#2]
Data is passed down from `src/App.tsx` as a prop, and is of type `DB` from `src/types.ts`.
Based on this data, we need to adapt the HHI code to, based on the new data type:
- [x] Display pins for each Incident
- [x] Show incident info in the side panel that opens up, including Type and Category info (styling can be same as HHI)

**Comment by the-snesler** [comment]
Working on this. I have it displaying pins for the dummy data.

- [x] Support multiple pins for a single incident
