### ISSUE TITLE
Mockup of statistics dashboard

### ISSUE THREAD

**Issue by the-snesler** [DSSD-Madison/Red-CORAL#51]
See #7 and [figma link](https://www.figma.com/design/ALwLKSqW9pv6VIRhWiU2KE/Red-Coral-Stats-Page?node-id=0-1&node-type=canvas&t=H0KpjOWbzV4XICDj-0).
The data has a couple attributes:
- Category (enum)
- Subtype within category
- Country/Department/Municipality (predefined text from [this file](https://github.com/DSSD-Madison/Red-CORAL/blob/main/src/colo_municips.json))
- Date
- Location as lat/long
- Description (free text field)

Frederic wants the dashboard to be flexible to their needs and be able to answer a couple types of questions:
- Simple number/category questions
  -  Given filter, what is the count of results?
  - Given filter, what is the most common value of another attribute?
  - Given filter, what percent of events are matched?
- Table of events that match a filter
- Line Graph of Number of Incidents (meeting selected filters) for each year in the selected year range

Filters are going to be a big part of whatever solution we end up with. I like the way Notion handles the UI for filtering large tables of data:
![Notion_tu3fRK17UZ](https://github.com/user-attachments/assets/52ddbde6-5ba8-4680-a245-6b4b24ab5a93)
Because we'll have lots of different styles of displaying data, I think having a couple sizes of "widget" (see below) could be good, but it's up to you!
![image](https://github.com/user-attachments/assets/cd121427-0d7e-414a-931f-eabcdd1f23c2)

**Comment by LostBitset** [comment]
Filters:

| Attribute | Filter |
|--------|--------|
| Category | (Enum) |
| Subtype | (Enum, sort by category?) |
| Country/Dpt/Muncipality | Three panes of dropdowns |
| Date | Single Date and probably a Date Range? |
| Location | (None) |
| Description | Contains... |

**Comment by the-snesler** [comment]
The mockup looks great, and we'll probably move forward with a variation on this design. Nice work!
